### ISSUE TITLE
Function call in a64 assembler outputs incorrectly

### ISSUE THREAD

**Issue by akkaze** [asmjit/asmjit#339]
#include <arm_neon.h>
#include <asmjit/a64.h>
#include <asmjit/core.h>

using namespace asmjit;
typedef void (*Func)(const void *);

void PrintInt32(int32_t a) { printf("%d\n", a); }

int main() {
  JitRuntime rt;   // Runtime specialized for JIT code execution.
  CodeHolder code; // Holds code and relocation information.

  code.init(rt.environment()); // Initialize code to match the JIT environment.
  a64::Compiler cc(&code);     // Create and attach x86::Compiler to code.
  cc.addFunc(FuncSignatureT<void, const void *>());

  arm::Gp src1 = cc.newUIntPtr("src1");

  cc.setArg(0, src1);

  arm::Gp e = cc.newInt32();
  cc.mov(e, 10);
	arm::Gp fn = cc.newUIntPtr();
  
  cc.mov(fn, (uint64_t)PrintInt32);
  InvokeNode* invokeNode;
  cc.invoke(&invokeNode, fn, FuncSignatureT<void, int>(CallConv::kIdHost));
  invokeNode->setArg(0, e);

  arm::Vec v1 = cc.newVecQ("vec1");
  cc.ldr(v1, arm::ptr(src1));

  cc.endFunc();
  cc.finalize();

  Func func;
  Error err = rt.add(&func, &code);
  float a[] = {1, 2, 3, 4};
  func(a);
  return 0;
}

This is my piece of code. I try to log value in a general purpose register. However, when I try to load into a vector register, this log will give me a incorrect number, which is more like a random number.Can you fix this bug.

**Comment by kobalicek** [comment]
It would be nice to have a full repro case, but I think I understand the problem from the description.

**Comment by akkaze** [comment]
This code will run on any aarch64 machine.
remove these two lines of code
arm::Vec v1 = cc.newVecQ("vec1");
cc.ldr(v1, arm::ptr(src1));
I got the correct output, However with it, the program outputs incorrectly

**Comment by kobalicek** [comment]
This should be fixed in `aarch64_refactor` branch.

**Comment by akkaze** [comment]
Still, this bug is not fixed.Without the ldr operation, this program outputs 10. However, with it , the output is 25254080

**Comment by kobalicek** [comment]
Could you post a full example demonstrating the problem? I added two Compiler tests, but maybe I missed something.

**Comment by kobalicek** [comment]
Could you please test the latest `aarch64` branch and confirm it's still present / it has been fixed?

**Comment by kobalicek** [comment]
I'm not sure whether to keep this open. AArch64 support has been merged, do you still have problems with function calls?

**Comment by kobalicek** [comment]
Closing as this seems to be working properly, please reopen if you are still having issues.
